name: pr_to_main

on:
  push:
    branches:
      - 'dev'

permissions:
  pull-requests: write

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: git checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      
      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request with reposync action
        id: open-pr
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 #v2.12.1
        with:
          github_token: ${{ secrets.PR_TOKEN }}
          destination_branch: main
          pr_title: ${{ github.event.commits[0].message }}
          pr_body: "Automated Pull Request"
